trigger:
  - Feature/branchname
pool:
  vmImage: 'windows-latest'
 
variables:
  solution: '**/*.sln'
  project: '**/application.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  azureSubscription: 'your sbscription'
  appName: 'production'  
  system.debug: false  
  
stages:
- stage: build
  jobs:
  - job: run_build
    pool:
      vmImage: 'windows-latest'
    steps:
      - task: NuGetToolInstaller@1
        name: 'NuGetToolInstaller'
        displayName: 'NuGet tool installer'
     
      - task: NuGetCommand@2  
        inputs:  
            restoreSolution: '$(solution)'  

- stage: Publish
  dependsOn: build
  jobs:
  - job: run_publish
    pool:
      vmImage: 'windows-latest'
    steps:
    - download: current
    - task: DotNetCoreCLI@2
      name: 'Publish'
      displayName: 'Publish'
      inputs:
        command: 'publish'
        publishWebProjects: true
        projects: '$(project)'
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
      inputs:
          SourceFolder: '$(system.defaultworkingdirectory)'
          Contents: '**\bin\$(BuildConfiguration)\**'
          TargetFolder: '$(build.artifactstagingdirectory)'

    - task: PublishBuildArtifacts@1
      name: 'PublishBuildArtifacts'
      displayName: 'Publish build artifacts'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        publishLocation: Container
        ArtifactName: 'WebApp'
        TargetPath: '$(Build.ArtifactStagingDirectory)'

       

- stage: Deploy
  jobs:
  - job: Deploy
    pool:
      vmImage: 'windows-latest'
    steps:
      - task: DownloadBuildArtifacts@1  
        inputs:  
            buildType: 'current'  
            downloadType: 'single'  
            downloadPath: '$(Build.ArtifactStagingDirectory)'  
            ArtifactName: 'WebApp'
            
      - task: AzureRmWebAppDeployment@4
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: 'Production'
          appType: 'webApp'
          WebAppName: 'production'
          deployToSlotOrASE: true
          ResourceGroupName: 'Production'
          SlotName: 'production'
          enableCustomDeployment: true
          packageForLinux: $(Build.ArtifactStagingDirectory)/**/*.zip
          DeploymentType: webDeploy
    
